### ISSUE TITLE
Hello, I don't seem to see Service Worker on the sample site  https://eleventy-plugin-pwa-v2-demo.lkmt.us/

### ISSUE THREAD

**Issue by xiyuvi** [lwojcik/eleventy-plugin-pwa-v2-demo#3]
Hello, I don't seem to see Service Worker on the sample site

https://eleventy-plugin-pwa-v2-demo.lkmt.us/

**Comment by lwojcik** [comment]
Hi, thanks for letting me know! Fixed.
